- {name: ImageNet100, mode: TV, seed: "1"}
- {name: ImageNet100, mode: TV, seed: "2"}
- {name: ImageNet100, mode: TV, seed: "3"}
- {name: ImageNet100, mode: TV, seed: "4"}
- {name: ImageNet100, mode: TV, seed: "5"}
- {name: ImageNet100, mode: BV, seed: "1"}
- {name: FARE4,       mode: RV, seed: "1"}
